### ISSUE TITLE
Review of my Kanban board project

### ISSUE THREAD

**Issue by oluyaratosin123** [oluyaratosin123/setup-kanbanBoard#20]
This is a setup for my Kanban board project, 

Here is the link to my created project: https://github.com/oluyaratosin123/setup-kanbanBoard/projects/1

For this project student success has told me to do it solo, 
Here is an evidence: 

Anne-Lore De Vreese
21 hours ago
Hello Edward, 

For the capstone project, please complete only the Kanban cards that are assigned to you. Leave a note in your PR that Student Success has allowed you to work solo. 

Kind Regards, 

Anne-Lore De Vreese (she/her)
Student Success |
Microverse

**Comment by elyor-doniyorov** [comment]
Hi @oluyaratosin123, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
_Thanks for that you provided the message on the PR from Student Success_ 
## Required Changes ♻️
- [ ] Your board should be a copy of this template board: [https://github.com/microverseinc/curriculum-javascript/projects/1](https://github.com/microverseinc/curriculum-javascript/projects/1). 
- [ ] Your team consists of only one, I think you will have an overall 10 tasks = 5 group tasks + 5 Student A tasks. Kindly copy the tasks from the above link given.
- [ ] Also do not forget to assign them to yourself;

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oluyaratosin123** [comment]
All required changes has  been done ✔️,
Here is the updated link to my Kandan board project: https://github.com/oluyaratosin123/setup-kanbanBoard/projects/1
I would really consider your feedback

**Comment by AshakaE** [comment]
### Hi @oluyaratosin123   🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
